version: 2
updates:
  - package-ecosystem: cargo
    directory: /
    schedule:
      interval: daily
    commit-message:
      prefix: ''
    labels: []
  # crates with [workspace] table are not recognized by the above 'directory: /'
  - package-ecosystem: cargo
    directory: /fuzz
    schedule:
      interval: daily
    commit-message:
      prefix: ''
    labels: []
